- vocabularies/Org.OData.Authorization.V1.json
- vocabularies/Org.OData.Authorization.V1.md
- vocabularies/Org.OData.Authorization.V1.xml
Approved as applied. 2018-18-1
> Applied https://issues.oasis-open.org/browse/ODATA-1124

- vocabularies/Org.OData.Capabilities.V1.json
- vocabularies/Org.OData.Capabilities.V1.md
- vocabularies/Org.OData.Capabilities.V1.xml
> Applied https://issues.oasis-open.org/browse/ODATA-1134

- vocabularies/Org.OData.Authorization.V1.json
- vocabularies/Org.OData.Authorization.V1.md
- vocabularies/Org.OData.Authorization.V1.xml
Add support for defining and applying named authorization schemes, as per ODATA-1145.
Still needs updates to Org.OData.Authorization.V1.json and Org.OData.Authorization.V1.md
> ODATA-1145

- vocabularies/Org.OData.Capabilities.V1.json
- vocabularies/Org.OData.Capabilities.V1.xml
Applied https://issues.oasis-open.org/browse/ODATA-1192
> ODATA-1192

- vocabularies/Org.OData.Capabilities.V1.json
- vocabularies/Org.OData.Capabilities.V1.md
- vocabularies/Org.OData.Capabilities.V1.xml
Proposal for https://issues.oasis-open.org/browse/ODATA-1167
> ODATA-1167

- vocabularies/Org.OData.Aggregation.V1.json
- vocabularies/Org.OData.Aggregation.V1.md
- vocabularies/Org.OData.Aggregation.V1.xml
- vocabularies/Org.OData.Authorization.V1.json
- vocabularies/Org.OData.Authorization.V1.md
- vocabularies/Org.OData.Authorization.V1.xml
- vocabularies/Org.OData.Capabilities.V1.json
- vocabularies/Org.OData.Capabilities.V1.md
- vocabularies/Org.OData.Capabilities.V1.xml
- vocabularies/Org.OData.Core.V1.json
- vocabularies/Org.OData.Core.V1.md
- vocabularies/Org.OData.Core.V1.xml
- vocabularies/Org.OData.Validation.V1.json
- vocabularies/Org.OData.Validation.V1.md
- vocabularies/Org.OData.Validation.V1.xml
Explicit Nullable for Booleans and Collections
> ODATA-1193

- examples/Org.OData.Capabilities.V1.permissions-sample.xml
- vocabularies/Org.OData.Capabilities.V1.xml
updating permissions sample, property name and type to address the issue logged via issue [https://github.com/oasis-tcs/odata-vocabularies/issues/53](https://github.com/oasis-tcs/odata-vocabularies/issues/53)
> ODATA-1316 - applied - Should support multiple permissions for read/write

- vocabularies/Org.OData.Core.V1.json
- vocabularies/Org.OData.Core.V1.md
- vocabularies/Org.OData.Core.V1.xml
See https://issues.oasis-open.org/browse/ODATA-1334
> ODATA-1334 - new - Mismatch in ModificationException term naming

- vocabularies/Org.OData.Aggregation.V1.json
- vocabularies/Org.OData.Aggregation.V1.md
- vocabularies/Org.OData.Aggregation.V1.xml
Marked values where mandatory as Nullable=false
> ODATA-1402

- vocabularies/Org.OData.Aggregation.V1.json
- vocabularies/Org.OData.Aggregation.V1.xml
[ODATA-1440](https://issues.oasis-open.org/browse/ODATA-1440)
> ODATA-1440 - resolved - CustomAggregate: remove AppliesTo="ComplexType"

- examples/Org.OData.Core.V1.GeometryFeature-sample.json
- examples/Org.OData.Core.V1.GeometryFeature-sample.md
- examples/Org.OData.Core.V1.GeometryFeature-sample.xml
- vocabularies/Org.OData.Core.V1.json
- vocabularies/Org.OData.Core.V1.md
- vocabularies/Org.OData.Core.V1.xml
Resolves https://issues.oasis-open.org/browse/ODATA-1461
> ODATA-1461 - new - Term describing GeoJSON Feature Objects

- vocabularies/Org.OData.Capabilities.V1.json
- vocabularies/Org.OData.Capabilities.V1.md
- vocabularies/Org.OData.Capabilities.V1.xml
- vocabularies/Org.OData.Core.V1.json
- vocabularies/Org.OData.Core.V1.md
- vocabularies/Org.OData.Core.V1.xml
> Core, Capabilities: improve description of LongDescription

- examples/Org.OData.Aggregation.V1.SalesModel-sample.json
- examples/Org.OData.Aggregation.V1.SalesModel-sample.xml
- vocabularies/Org.OData.Aggregation.V1.json
- vocabularies/Org.OData.Aggregation.V1.md
- vocabularies/Org.OData.Aggregation.V1.xml
https://issues.oasis-open.org/browse/ODATA-1468
Adapt example model to new [OData-Aggr, example 63].
> Digital/Physical -> Food/NonFood

- vocabularies/Org.OData.Aggregation.V1.md
- vocabularies/Org.OData.Aggregation.V1.xml
Since OData-Data-Aggr-4.0 CSD01 will not allow cycles.
> Don't mention the Cycle term

- .vscode/settings.json
- lib/cli.js
- package-lock.json
- package.json
> Fix: remove dependency to minimist

- lib/README.md
- package-lock.json
> pandoc needed for Markdown generation

- assets/template.html
See
* https://sansec.io/research/polyfill-supply-chain-attack
* https://www.youtube.com/watch?v=ILvNG1STUZU
> Update template.html - remove polyfill

- lib/csdl2markdown.js
Fixes https://github.com/SAP/odata-vocabularies/issues/330
> Check for pandoc

- vocabularies/Org.OData.Capabilities.V1.json
- vocabularies/Org.OData.Capabilities.V1.md
- vocabularies/Org.OData.Capabilities.V1.xml
> Allow ne in MultiRange

- assets/darkmode.html
- lib/csdl2markdown.js
- lib/pages.js
- Provide aria-label for the "Light/dark mode" switch
- Set page language
> Improve accessibility

- lib/csdl2markdown.js
- test/csdl2markdown.test.js
- vocabularies/Org.OData.Capabilities.V1.md
Adhere to https://dequeuniversity.com/rules/axe/4.10/definition-list
> Make <dl> accessible
